### ISSUE TITLE
Allow user to Drag-and-Drop extract, ignoring folders above the current one

### ISSUE THREAD

**Issue by RibShark** [giorgiotani/PeaZip#4]
An example. Let's say I have a 7z file, which contains a folder named "test" and inside that folder, a file named "test.txt". Currently, if I were to select the file named "test.txt" and extract it using drag-and-drop into a folder on my hard drive, it would copy the "test" folder into the folder on my hard drive, when I am looking for PeaZip to copy the "text.txt" file. I hope this is clear enough explaination, and I would love for this option to be included.

**Comment by lolfood** [comment]
Yes please. It's super annoying when modding games.

**Comment by lolfood** [comment]
I FOUND THE SOLUTION. Go to Options > Settings > Archive Manager > Extract > Always ignore paths for drag and drop extraction.

**Comment by gazugafan** [comment]
Actually, this option only appears to solve the issue when you are dragging file(s). If a folder is part of the selection you are dragging, this option seems to be ignored. Is this intentional for some reason?
